import { defineConfig } from "bun:test";

export default defineConfig({
  test: {
    globals: true,
    coverage: true,
    coverageThreshold: {
      global: {
        branches: 70,
        functions: 70,
        lines: 70,
        statements: 70,
      },
    },
    setupFiles: ["./src/lib/__tests__/setup.ts"],
    environment: "node",
    reporter: "tap",
    verbose: true,
  },
});
